// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmWGp5bIROGiRA-4ocU5f94R3GNbnddwk',
    appId: '1:922859701842:android:6a1f2967362e33b2cc018b',
    messagingSenderId: '922859701842',
    projectId: 'intense-signer-345710',
    databaseURL: 'https://intense-signer-345710-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'intense-signer-345710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh-ElEd2k3DnRvae2b2YNjEIyDYCPKT9w',
    appId: '1:922859701842:ios:bca23b476458cb44cc018b',
    messagingSenderId: '922859701842',
    projectId: 'intense-signer-345710',
    databaseURL: 'https://intense-signer-345710-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'intense-signer-345710.appspot.com',
    iosBundleId: 'com.f2f.uneeds',
  );
}
